{% set name = "molfeat" %}
{% set version = "1.0.0" %}
{% set python_max = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/molfeat-{{ version }}.tar.gz
  sha256: 888c94b3a09e480119950ae4089c6d7a6196bba4264e00985ca6bc1872265ee9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<={{ python_max }}
    - tqdm
    - pyyaml
    - loguru
    - joblib
    - filelock
    - fsspec >=2021.9
    - s3fs >=2021.9
    - gcsfs >=2021.9
    - platformdirs
    - python-dotenv

    # Scientific
    - pandas
    - numpy
    - scipy
    - h5py
    - pyarrow
    - matplotlib-base
    - pydantic >=2.0.0

    # Chemistry
    - datamol >=0.8.0
    - rdkit >=2021.09
    - pmapper
    - mordredcommunity

    # ML
    - pytorch >=1.13
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - molfeat
  # requires:
  #   - pytest
  # source_files:
  #   - tests/
  # commands:
  #   - pytest --verbose tests/

about:
  home: https://github.com/datamol-io/molfeat
  summary: A python library to featurize molecules.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cwognum
    - maclandrol
